name: Static type check

on:
  pull_request:
    paths:
      - nonebot_plugin_styledstr/**

jobs:
  pyright:
    name: Static type check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install .
      - uses: jordemort/action-pyright@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          lib: true
